### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" 

### ISSUE THREAD

**Issue by cerhai** [tshaddix/react-chrome-redux#132]
Platform: MacOS Sierra
node: v8.9.4
npm: 5.6.0

I got this error when I run `npm run webpack`
```
ERROR in ./node_modules/react-chrome-redux/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-async-to-generator" specified in "/Users/cerhai/git/test/node_modules/react-chrome-redux/.babelrc" at 0, attempted to resolve relative to "/Users/cerhai/git/test/node_modules/react-chrome-redux"
    at /Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/cerhai/git/test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/cerhai/git/test/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/cerhai/git/test/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/cerhai/git/test/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ ./event/src/index.js 9:24-53
```

My package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "webpack": "./node_modules/.bin/webpack -w"
  },
  "author": "Cerhai",
  "license": "ISC",
  "dependencies": {
    "react": "^15.5.0",
    "react-chrome-redux": "^1.5.0",
    "react-dom": "^15.5.0",
    "react-redux": "^4.0.0",
    "redux": "^3.0.4",
  },
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.7",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.1",
    "webpack": "^3.10.0"
  }
}
```
What's wrong? Does anyone know the solution?

**Comment by tshaddix** [comment]
It looks like your webpack config is trying to run babel with the config in `react-chrome-redux`. What does your webpack config look like?

**Comment by tshaddix** [comment]
@cerhai closing for now. Let us know if you're still running into this issue!
